# .github/workflows/workflow.yml
jobs:
    deployment_job:
        steps:
            - actions/checkout@v1
            - uses: shivammathur/setup-php@master
                with: 
                    php-version: 7.3
            - run: composer install
            # Make sure the @0.3.1 matches the current version of the action
            # You can also use `master`, but it's best to lock to a specific version
            - uses: atymic/deployer-php-action@0.3.1
              with:
                  ssh-private-key: ${{ secrets.PRIVATE_KEY }}
                  ssh-known-hosts: ${{ secrets.KNOWN_HOSTS }}
                  # To disable host key checking (insecure!):
                  ssh-disable-host-key-checking: true
            
